name: polyseed
description: A pure dart implementation of the 16-word seed scheme for monero
version: 0.0.2
homepage: https://cakelabs.com
repository: https://github.com/cake-tech/polyseed_dart
issue_tracker: https://github.com/cake-tech/polyseed_dart/issues

environment:
  sdk: ^3.0.6

dependencies:
  pointycastle: ^3.7.3
  hashlib: ^1.12.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
